Move to RSS and HeapAlloc
Dieterbe/profiletrigger pull request #3
Opened 2018-09-17 13:36 UTC by gouthamve

This is a little invasive, I'll integrate into the cortex-querier and update here.

2018-09-25 18:29 UTC, tomwilkie commented
Tried this out on Prometheus today, LGTM!

2018-11-19 12:00 UTC, Dieterbe requested changes
needs changes

2018-11-19 12:00 UTC, Dieterbe commented on cmd/demo-heap/main.go
> +		CheckEvery:     time.Duration(1) * time.Second,
don't need the `time.Duration()`. the type is inferred from the time.Second constant

2018-11-19 12:00 UTC, Dieterbe commented on cmd/demo-heap/main.go
> +		log.Println("profiletrigger heap saw error:", e)
why this change?

2018-11-19 12:00 UTC, Dieterbe commented on heap/heap.go
> +	"github.com/prometheus/procfs"
i don't want to pull in this dependency.
we've pulled that package in in some other projects and it's always a huge battle between dep and the fixtures directory which contains a bunch of symlinks which breaks a bunch of other tools.

can we just copy the small piece of code we need?

2018-11-19 12:00 UTC, Dieterbe commented on heap/heap.go
> +		lastTriggered: time.Now().Add(-cfg.MinTimeDiff),
why introduce a fake/incorrect value when we can simply rely on the zero value like we did before?

2018-11-19 12:00 UTC, Dieterbe commented on heap/heap.go
> +		heap.logError(err)
the asynchronous feeding back of errors to the caller is for stuff that happens after construction time.
for errors known at construction time, we should just return them to the caller.
in particular, if we know at construction time that we won't be able to honor the requested threshold, the caller should know right then and there.

2018-11-19 12:00 UTC, Dieterbe commented on heap/heap.go
> +		case heap.Errors <- err:
why silently drop errors? it's the caller responsibility to read the errors (if a non-nil chan was provided)

2018-11-19 12:00 UTC, Dieterbe commented on heap/heap.go
> +	RSSThreshold   int
perhaps this is personal preference, but when words are partially the same, i like to make that clearer and consistent by starting with the part that is identical.
e.g. i would name these
```
ThreshAlloc
ThreshRSS
```

2018-11-19 12:00 UTC, Dieterbe commented on heap/heap.go
>  // Heap will check every checkEvery for memory obtained from the system, by the process
the docs/comments need to be updated

2018-11-19 12:00 UTC, Dieterbe commented on heap/heap.go
> +	RSSThreshold   int
also can you add a comment for both to describe whether they should be in bytes or in another unit.

2018-12-04 14:53 UTC, Dieterbe commented
@gouthamve any plans to finish this?

2018-12-19 12:38 UTC, Dieterbe approved these changes

2018-12-19 12:38 UTC, merged